name: 'Plain dotenv input parser Github action'
author: 'Luiz Felipe Laviola'
description: |-
  Parse plain .env input and set as environment secrets

branding:
  icon: 'package'
  color: 'blue'

inputs:
  data:
    description: The doenv syntax string to be parsed
    required: true

  parse-env:
    description: Sets whether the action should pass the content to build environment
    required: false
    default: 'true'

  write-env-file:
    description: Sets whether the action should write a .env file with the content
    required: false
    default: 'false'

  env-file-path:
    description: Sets the path of the .env file to be written
    required: false
    default: '.env'

runs:
  using: 'node16'
  main: 'dist/index.js'