name: 'Plain dotenv input parser Github action'
author: 'Luiz Felipe Laviola'
description: |-
  Parse plain .env input and set as environment secrets

branding:
  icon: 'package'
  color: 'blue'

inputs:
  data:
    description: |-
      Text input following the dotenv format
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'